repos:
  # Python formatters
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.10
        args: ["--line-length", "120"]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "120"]

  # Python linters
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format

  # YAML validation and general checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: detect-private-key
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-ast
      - id: debug-statements

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint-docker
        entry: hadolint/hadolint:v2.12.0 hadolint
        language: docker_image
        types: ["dockerfile"]
        args: ["--ignore", "DL3008", "--ignore", "DL3009", "--ignore", "DL3013"]

  # Secret detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: .*\.lock|package-lock\.json|.*\.min\.js

  # Local custom hooks
  - repo: local
    hooks:
      - id: no-env-files
        name: Block .env files
        entry: '.env files must not be committed'
        language: fail
        files: '^\.env$|^\.env\.(?!example$).*'
        exclude: '^\.env\.example$'
      - id: no-local-yml
        name: Block *.local.yml files
        entry: 'Local override files must not be committed'
        language: fail
        files: '.*\.local\.ya?ml$'

# Configuration
default_language_version:
  python: python3.10

fail_fast: false
