global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # vLLM service metrics
  - job_name: 'vllm'
    static_configs:
      - targets: ['vllm:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # NVIDIA DCGM GPU metrics
  - job_name: 'dcgm'
    static_configs:
      - targets: ['dcgm-exporter:9400']
    scrape_interval: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter (if deployed)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
