apiVersion: v1
kind: ConfigMap
metadata:
  name: vllm-config
  namespace: vllm
data:
  MODEL_PATH: "TheBloke/Mistral-7B-Instruct-v0.2-AWQ"
  GPU_MEMORY_UTILIZATION: "0.9"
  MAX_NUM_SEQS: "32"
  BLOCK_SIZE: "16"
  SWAP_SPACE: "4"
  QUANTIZATION: "awq"
  DTYPE: "float16"
  MAX_CONTEXT_LEN: "4096"
  VLLM_ATTENTION_BACKEND: "SDPA"  # T4-optimized backend
