apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vllm

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
  - servicemonitor.yaml

images:
  - name: vllm-service
    newTag: latest

configMapGenerator:
  - name: vllm-config
    behavior: merge
    literals:
      - LOG_LEVEL=INFO

labels:
  - pairs:
      environment: production
      team: ml-platform
    includeSelectors: true
    includeTemplates: true
