apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vllm-rolebinding
  namespace: vllm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vllm-role
subjects:
- kind: ServiceAccount
  name: vllm-sa
  namespace: vllm
